# Prefix
unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix

# Reload config
unbind r
bind r source-file ~/.tmux.conf

# Basic
setw -g pane-base-index 1
set-window-option -g mode-keys vi 
set -g escape-time 50
set -g history-limit 10000
set -g base-index 1
set -g mouse off
set -g renumber-windows on
set -g display-time 2000
# set -g status-interval 5
set -s set-clipboard on

# Don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
set -g monitor-activity off
set -g bell-action none

# Keys
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "clip.exe"
bind-key S command-prompt -I "#S" "rename-session '%%'"
bind-key W command-prompt -I "#W" "rename-window '%%'"

# STATUS BAR
set -g status-position bottom
set -g status-justify left
set -g status-style "bg=default,fg=#DCD7BA"
set -g status-left "#{?client_prefix,#[bg=#957FB8]#[fg=#16161D],#[fg=#957FB8]#[bg=default]} #S "
setw -g window-status-format "#[fg=#727169,bg=default] #I:#W #[default]"
setw -g window-status-current-format "#[fg=#DCD7BA,bg=default,bold] #I:#W #[default]"
set -g status-right "#[fg=#76946A]%H:%M#[fg=#727169] #H"
set -g pane-border-style "fg=#1F1F28"
set -g pane-active-border-style "fg=#658594"
set -g message-style "bg=default,fg=#FFA066"
setw -g mode-style "bg=default,fg=#FFA066,bold"

# Plugins
set -g @plugin "tmux-plugins/tpm" # must go 1st
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'omerxx/tmux-sessionx'

# RESURRECT & CONTINUUM
set -g @continuum-restore 'on'
set -g @continuum-save-interval '5'

# TMUX-SESSIONX
set -g @sessionx-bind 'O'
set -g @sessionx-prefix on
set -g @sessionx-filter-current 'false'
set -g @sessionx-zoxide-mode 'on'
set -g @sessionx-tree-mode 'off'
set -g @sessionx-preview-enabled 'true'
set -g @sessionx-preview-location 'right'
set -g @sessionx-preview-ratio '70%'
set -g @sessionx-window-width '80%'
set -g @sessionx-window-height '90%'

# Plugin manager - must go last
run '~/.tmux/plugins/tpm/tpm'
